export const menuList = [
  {
    id: 1,
    logoSrc: "/menu_images/menu.png",
    name: "All Menu",
  },
  {
    id: 2,
    logoSrc: "/menu_images/coffee.png",
    name: "Coffee",
  },
  {
    id: 3,
    logoSrc: "/menu_images/non-coffee.png",
    name: "Non-Coffee",
  },
  {
    id: 4,
    logoSrc: "/menu_images/pastry.png",
    name: "Pastries",
  },
  {
    id: 5,
    logoSrc: "/menu_images/sandwhich.png",
    name: "Sandwiches",
  },
];

export const coffeeList = [
  {
    id: 1,
    name: "Caffe Latte",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/1.png",
    category: "coffee",
  },
  {
    id: 2,
    name: "Cappuccino",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/2.png",
    category: "coffee",
  },
  {
    id: 3,
    name: "Flat White",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/3.png",
    category: "coffee",
  },
  {
    id: 4,
    name: "Caffe Mocha",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/4.png",
    category: "coffee",
  },
  {
    id: 5,
    name: "Espresso",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/5.png",
    category: "coffee",
  },
  {
    id: 6,
    name: "Caramel Macchiato",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/6.png",
    category: "coffee",
  },
  {
    id: 7,
    name: "Americano",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/7.png",
    category: "coffee",
  },
  {
    id: 8,
    name: "Cortado",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/8.png",
    category: "coffee",
  },
  {
    id: 9,
    name: "Irish Coffee",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/9.png",
    category: "coffee",
  },
  {
    id: 10,
    name: "Turmeric Latte (Golden Milk)",
    price: 169,
    quantity: 10,
    imageSrc: "/coffee/10.png",
    category: "coffee",
  },
];

export const nonCoffeeList = [
  {
    id: 1,
    name: "Hot Chocolate",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/1.png",
    category: "non_coffee",
  },
  {
    id: 2,
    name: "Matcha Latte",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/2.png",
    category: "non_coffee",
  },
  {
    id: 3,
    name: "Spiced Chai Latte",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/3.png",
    category: "non_coffee",
  },
  {
    id: 4,
    name: "London Fog",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/4.png",
    category: "non_coffee",
  },
  {
    id: 5,
    name: "Iced Hibiscus Berry Tea",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/5.png",
    category: "non_coffee",
  },
  {
    id: 6,
    name: "Mango Lassi",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/6.png",
    category: "non_coffee",
  },
  {
    id: 7,
    name: "Lemonade",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/7.png",
    category: "non_coffee",
  },
  {
    id: 8,
    name: "Golden Milk Latte",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/8.png",
    category: "non_coffee",
  },
  {
    id: 9,
    name: "Iced Rose Milk Tea",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/9.png",
    category: "non_coffee",
  },
  {
    id: 10,
    name: "Iced Peach Green Tea",
    price: 169,
    quantity: 10,
    imageSrc: "/non_coffee/10.png",
    category: "non_coffee",
  },
];
export const pastryList = [
  {
    id: 1,
    name: "classic buttery croissant",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/1.png",
    category: "pastry",
  },
  {
    id: 2,
    name: "flaky pain au chocolat",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/2.png",
    category: "pastry",
  },
  {
    id: 3,
    name: "berry-topped Danish pastry",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/3.png",
    category: "pastry",
  },
  {
    id: 4,
    name: "classic glazed cinnamon roll",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/4.png",
    category: "pastry",
  },
  {
    id: 5,
    name: "almond croissant with sliced almonds",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/5.png",
    category: "pastry",
  },
  {
    id: 6,
    name: "classic blueberry muffin",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/6.png",
    category: "pastry",
  },
  {
    id: 7,
    name: "savory cheese and chive scone",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/7.png",
    category: "pastry",
  },
  {
    id: 8,
    name: "slice of crumb coffee cake",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/8.png",
    category: "pastry",
  },
  {
    id: 9,
    name: "raspberry almond macaron",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/9.png",
    category: "pastry",
  },
  {
    id: 10,
    name: "raspberry almond macaron",
    price: 169,
    quantity: 10,
    imageSrc: "/pastry/10.png",
    category: "pastry",
  },
];

export const sandwichList = [
  {
    id: 1,
    name: "Mediterranean classic",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/1.png",
    category: "sandwich",
  },
  {
    id: 2,
    name: "essential breakfast sandwich",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/2.png",
    category: "sandwich",
  },
  {
    id: 3,
    name: "hearty, rustic choice",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/3.png",
    category: "sandwich",
  },
  {
    id: 4,
    name: " fresh vegan option",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/4.png",
    category: "sandwich",
  },
  {
    id: 5,
    name: " Italian classic, toasted",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/5.png",
    category: "sandwich",
  },
  {
    id: 6,
    name: "smoky, savory lunch",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/6.png",
    category: "sandwich",
  },
  {
    id: 7,
    name: "dynamic, zesty bite",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/7.png",
    category: "sandwich",
  },
  {
    id: 8,
    name: "smoky, colorful lunch",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/8.png",
    category: "sandwich",
  },
  {
    id: 9,
    name: "ultimate comfort food",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/9.png",
    category: "sandwich",
  },
  {
    id: 10,
    name: "ultimate comfort food",
    price: 169,
    quantity: 10,
    imageSrc: "/sandwich/10.png",
    category: "sandwich",
  },
];

export interface CheckoutSessionResponse {
  url: string;
}
